### ISSUE TITLE
some docker issues

### ISSUE THREAD

**Issue by khoa-p** [joshstevens19/rindexer#113]
Hey! I'm trying to start a project using `rindexer` and am having trouble getting the docker setup right. I have a generated `rindexer.yaml` file that I made via the CLI locally and am trying to deploy this to the cloud, with a self-hosted postgres instance (in another container).

Currently our docker-compose looks something like:

```
services:
  indexer:
    image: ghcr.io/joshstevens19/rindexer
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
        - ./abis:/app/project_path/abis
        - ./rindexer.yaml:/app/project_path/rindexer.yaml
        - ./.env:/app/project_path/.env
    env_file: .env
    working_dir: /app/project_path
    entrypoint: /app/rindexer
    command: start -p /app/project_path all

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
volumes:
  postgres-data:
```

This seems to start the indexer fine, but I believe this image doesn't contain the graphql binaries so we get something like:

```
rindexer-swap-volume-indexer-1   | 24 October - 19:13:06.859643 ERROR Failed to start GraphQL server: GraphQLServerStartupError("rindexer-graphql executable not found")
```

I tried replacing the image with `ghcr.io/joshstevens19/rindexer-bundled`, which seems to start everything up just fine... but the indexer doesn't run. 

```
rindexer-swap-volume-indexer-1   | 24 October - 19:12:20.861952  INFO Starting GraphQL server
rindexer-swap-volume-indexer-1   | 24 October - 19:12:20.862988  INFO Temp dropping constraints relationships from the database for historic indexing for speed reasons
<no further output>
```

Any guidance would be appreciated, thanks!

**Comment by joshstevens19** [comment]
Yeah so rindexer-bundled has the graphql alongside it so that is the correct docker image to use if you need the graphql part 

the above looks like a connection timeout as it hangs here is the database url you defined in .env fully correct? Aka if you take this database connection string and try to connect to it via psql or locally running an rindexer does it work?

**Comment by khoa-p** [comment]
Let me make sure, I was having trouble with connecting to the db before which would spit out an error message before even starting indexing. I'm not seeing that anymore so I'm assuming the connection to the db is fine

**Comment by khoa-p** [comment]
For reference my env file looks like:

```
DATABASE_URL=postgresql://postgres:rindexer@postgres:5432/postgres
POSTGRES_PASSWORD=rindexer
PROJECT_PATH=/app/project_path
```

**Comment by khoa-p** [comment]
Yup connections are fine:

```
postgres=# \dn
                    List of schemas
               Name                |       Owner
-----------------------------------+-------------------
 postgraphile_watch                | postgres
 public                            | pg_database_owner
 rindexer_internal                 | postgres
```

**Comment by joshstevens19** [comment]
If you comment out the rindexer stuff from the docker side and run Postgres only and then run rindexer locally using rindexer CLI it works as well?

**Comment by khoa-p** [comment]
I can try that real quick

**Comment by khoa-p** [comment]
Yep same behavior, what I did:

1. Commented out the rindexer stuff from my `docker-compose`
2. Changed the `.env` file to point to the new exposed port:

```
DATABASE_URL=postgresql://postgres:rindexer@localhost:5440/postgres
POSTGRES_PASSWORD=rindexer
```
3. `rindexer start all`

Directory structure:

```
ubuntu@ip-xxx-xxx-xx:~/rindexer-swap-volume$ find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
.
 |-abis
 | |-SovereignPool.abi.json
 |-docker-compose.yml
 |-.env
 |-rindexer.yaml
```

**Comment by joshstevens19** [comment]
Sorry I am on holiday till Monday so can’t debug here but: 

try this project it follows similar stuff to yours but a more slim docker file, does the same thing happen? 

https://github.com/joshstevens19/rindexer/tree/master/examples/rindexer_demo_cli

also what version of rindexer cli are you on ?

**Comment by khoa-p** [comment]
All good, thank you for the help! 

I'm on `rindexer 0.10.0` 

Ideally I don't wanna have to use the CLI, really want to dockerize everything for deployments to EC2

**Comment by khoa-p** [comment]
Yeah would rather not work with EKS if I don't need to. I'll try to run the example project and see what happens. Enjoy your vacation!

**Comment by joshstevens19** [comment]
Yeah if not please supply all the info you have including the rindexer.yaml - ABIs and full docker file (even a repo would be great) and il get it fixed for you on Monday thanks dude

**Comment by khoa-p** [comment]
Hey following up, I don't think I can share the ABI's (it seems to be finding it just fine). The full docker file is:

```
services:
  indexer:
    image: ghcr.io/joshstevens19/rindexer-bundled
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
        - ./abis:/app/project_path/abis
        - ./rindexer.yaml:/app/project_path/rindexer.yaml
        - ./.env:/app/project_path/.env
    env_file: .env
    working_dir: /app/project_path
    entrypoint: /app/rindexer
    command: start -p /app/project_path all

  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres-data:
```

The full `.env`:

```
DATABASE_URL=postgresql://postgres:rindexer@postgres:5432/postgres
POSTGRES_PASSWORD=rindexer
PROJECT_PATH=/app/project_path
```

The directory structure:

```
❯ tree .
.
├── abis
│   └── Pool.abi.json
├── docker-compose.yml
└── rindexer.yaml
```

**Comment by khoa-p** [comment]
Ah I forgot to include the rindexer.yaml file as well, here you go:

```
name: rindexer-swap-volume
project_type: no-code
networks:
  - name: ethereum
    chain_id: 1
    rpc: some_rpc
storage:
  postgres:
    enabled: true
contracts:
  - name: SovereignPool
    details:
      - network: ethereum
        address: addr
        start_block: 'block'
    abi: /app/project_path/abis/Pool.abi.json
    include_events:
      - Swap
graphql:
  port: 3001
```
