### ISSUE TITLE
Factory contract indexing

### ISSUE THREAD

**Issue by joshstevens19** [joshstevens19/rindexer#14]
Some contracts deploy contracts inside themselves and, in turn, then emit the new address for the indexing to listen out for. For example, Uniswap Pools is a good example, we should allow rindexer to support factory style track, a bit of work has already been done on this in the YAML itself it just needs the code to track it and index the new addresses as they are emitted.

**Comment by adapt7** [comment]
Is there any way currently to add new addresses (contracts) to watch dynamically, during the runtime (without need to restart whole service)?

**Comment by joshstevens19** [comment]
yaml design 

```yaml
contracts:
  - name: Factory
    details:
      - network: ethereum
        address: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
        factories:
          - name: pool
            created_event: 
              event: PoolCreated
              parameter_name: "poolAddress"
            abi: ./abis/uniswap-v3-pool.abi.json
            include_events:
              - Swap
              - Mint
        start_block: 12369621
    abi: ./abis/uniswap-factory.abi.json
    include_events:
      - PoolCreated
```
