### ISSUE TITLE
rindexer not persisting last synced block

### ISSUE THREAD

**Issue by khoa-p** [joshstevens19/rindexer#182]
Hey all! I've noticed that sometimes rindexer is not saving the last synced block. I've verified in logs that rindexer has seen much newer blocks as well. I haven't done a close read of the code yet -- but how often is this data persisted? Or is it only persisted upon shutdown, etc?

We've been using a self-hosted RPC, but pruning data >2 days old. Not persisting the last synced block means that upon restarting rindexer, it'll try to go to a pretty old block when our block ranges are pretty limited (or the block has been pruned).

**Comment by joshstevens19** [comment]
hey can i get your rindexer.yaml and all ABIs and how you are running it

**Comment by khoa-p** [comment]
Yeah here's the ABI:

[stHypeWithdrawalModule4.abi.json](https://github.com/user-attachments/files/19619127/stHypeWithdrawalModule4.abi.json)

And the rindexer.yaml:

```
name: rindexer
project_type: no-code
networks:
  - name: hyperliquid
    chain_id: 999
    rpc: https://hl-archive-node.xyz
storage:
  postgres:
    enabled: true
contracts:
  - name: StexAmmWithdrawalModuleHyperliquid0x40Ba056B004Edd0b572509A1276Fd8530cf2bb7f
    details:
      - network: hyperliquid
        address: 0x40Ba056B004Edd0b572509A1276Fd8530cf2bb7f
        start_block: 1937992
    abi: ./abis/stHypeWithdrawalModule4.abi.json
    include_events:
      - LPWithdrawalRequestClaimed
      - LPWithdrawalRequestCreated
    streams:
      sns: 
        aws_config:
          region: us-east-1
          access_key: ${AWS_ACCESS_KEY_ID}
          secret_key: ${AWS_SECRET_ACCESS_KEY}
        topics:
          - topic_arn: arn:aws:sns:us-east-1:xxx
            networks:
              - hyperliquid
            events:
              - event_name: LPWithdrawalRequestCreated
              - event_name: LPWithdrawalRequestClaimed
```

For some more context, I'm running this on AWS hooked up to RDS (postgres)
