### ISSUE TITLE
Rindexer stuck at `INFO Starting rindexer rust project` after `cargo run`

### ISSUE THREAD

**Issue by 0xethsign** [joshstevens19/rindexer#187]
this is my `rindexer.yaml` 
```
name: token
description: token events
project_type: rust
networks:
- name: ethereum
  chain_id: 1
  rpc: https://eth-mainnet.g.alchemy.com/v2/<redacted>
storage:
  postgres:
    enabled: true
native_transfers:
  enabled: false
contracts:
- name: USDT 
  details:
  - network: ethereum
    address: "0xdAC17F958D2ee523a2206206994597C13D831ec7" 
    start_block: '22400000'
  abi: ./abis/Usdt.abi.json
  include_events:
  - Transfer
  - Approval
```

and this is my .env 
```
DATABASE_URL=postgresql://<username>:<password>@localhost:5432/postgres
```

and this is my docker-compose.yml 
```
volumes:
  postgres_data:
    driver: local

services:
  postgresql:
    image: postgres:16
    shm_size: 1g
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5440:5432
    env_file:
      - ./.env
```

when i run `cargo run` or `rindexer start all`, i'm stuck at this - 
```
0xethsign@MacBook-Pro ~/project01/rindexer [master]× $ rindexer start all
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/token ''`
05 May - 17:21:33.194822  INFO Starting rindexer rust project
```
