### ISSUE TITLE
expose chain id in TxInformation

### ISSUE THREAD

**Issue by joshstevens19** [joshstevens19/rindexer#212]
in the rindexer yaml you define networks like

```yaml
networks:
  - name: ethereum
    chain_id: 1
    rpc: ${ETHEREUM_RPC_URL}
```

when an event is emitted it also bakes in tx information which looks like:

```rs
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TxInformation {
    pub network: String,
    pub address: Address,
    pub block_hash: BlockHash,
    pub block_number: U64,
    pub block_timestamp: Option<U256>,
    pub transaction_hash: TxHash,
    pub log_index: U256,
    pub transaction_index: U64,
}
```

We do not expose the chain_id here which is annoying as you may want to use it rather then your yaml name - we should expose it
