### ISSUE TITLE
Add upsert/aggregation support in no-code

### ISSUE THREAD

**Issue by joshstevens19** [joshstevens19/rindexer#26]
Right now, no-code indexing writes all the data to the database sometimes, people want aggregation/upsert with a single result row, even though its possible using SQL after the data we could make this even easier for people

example schema roughly:

```yaml
name: RocketPoolETHIndexer
description: Enhanced rindexer project with advanced aggregation features
repository: https://github.com/joshstevens19/rindexer
project_type: no-code
networks:
- name: ethereum
  chain_id: 1
  rpc: https://mainnet.gateway.tenderly.co
storage:
  postgres:
    enabled: true
    drop_each_run: true
contracts:
- name: RocketPoolETH
  details:
  - network: ethereum
    address: 0xae78736cd615f374d3085123a210448e74fc6393
    start_block: '18600000'
    end_block: '18718056'
  abi: ./abis/RocketTokenRETH.abi.json
  
  # Standard event logging (existing functionality)
  include_events:
    - Transfer
    - TokensMinted
    - TokensBurned
  
  # Enhanced custom indexing functionality
  custom_indexing:
    # Table for tracking individual address balances
    - name: token_balances
      description: "Tracks the current rETH balance for each address"
      fields:
        - name: address
          type: address
          primary: true
        - name: balance
          type: uint256
          default: 0
          index: true
        - name: first_activity
          type: timestamp
          update_on_insert: true
        - name: last_updated
          type: timestamp
          auto_update: true
        - name: role
          type: string
          default: "user"
      
      events:
        - event: Transfer
          mappings:
            - match: to
              conditions: 
                - "to != 0x0000000000000000000000000000000000000000"
                - "value > 0"
              updates:
                - field: balance
                  action: add
                  value: value
            
            - match: from
              conditions: "from != 0x0000000000000000000000000000000000000000"
              updates:
                - field: balance
                  action: subtract
                  value: value
    
    # Table for tracking whale accounts
    - name: whale_accounts
      description: "Tracks accounts with large rETH holdings"
      fields:
        - name: address
          type: address
          primary: true
        - name: balance
          type: uint256
          default: 0
        - name: whale_status
          type: string
          default: "small_holder"
        - name: percentage_of_supply
          type: float
          derived: "balance / {{token_supply.total_supply}} * 100"
      
      events:
        - event: Transfer
          mappings:
            - match: to
              conditions: "to != 0x0000000000000000000000000000000000000000"
              updates:
                - field: balance
                  action: add
                  value: value
                - field: whale_status
                  action: replace
                  value: "balance >= 1000000000000000000000 ? 'whale' : balance >= 100000000000000000000 ? 'medium_holder' : 'small_holder'"
            
            - match: from
              conditions: "from != 0x0000000000000000000000000000000000000000"
              updates:
                - field: balance
                  action: subtract
                  value: value
                - field: whale_status
                  action: replace
                  value: "balance >= 1000000000000000000000 ? 'whale' : balance >= 100000000000000000000 ? 'medium_holder' : 'small_holder'"
    
    # Separate table for token supply metrics
    - name: token_supply
      description: "Tracks global rETH supply metrics"
      fields:
        - name: id
          type: string
          primary: true
          default: "global"
        - name: total_supply
          type: uint256
          default: 0
        - name: total_minted
          type: uint256
          default: 0
        - name: total_burned
          type: uint256
          default: 0
        - name: last_updated
          type: timestamp
          auto_update: true
        - name: burn_ratio_percent
          type: float
          derived: "total_burned / NULLIF(total_minted, 0) * 100"
      
      events:
        - event: TokensMinted
          mappings:
            - match: id
              value: "global"
              updates:
                - field: total_supply
                  action: add
                  value: amount
                - field: total_minted
                  action: add
                  value: amount
        
        - event: TokensBurned
          mappings:
            - match: id
              value: "global"
              updates:
                - field: total_supply
                  action: subtract
                  value: amount
                - field: total_burned
                  action: add
                  value: amount
        
        - event: Transfer
          mappings:
            - match: id
              value: "global"
              conditions: "to == 0x0000000000000000000000000000000000000000"
              updates:
                - field: total_burned
                  action: add
                  value: value
                - field: total_supply
                  action: subtract
                  value: value
```
