### ISSUE TITLE
Filter to turn into an array to avoid repeating yaml 

### ISSUE THREAD

**Issue by joshstevens19** [joshstevens19/rindexer#40]
at the moment to define many filters in a contract you have to do:

```yaml
contracts: 
  - name: ERC20
    details:
      - network: ethereum
        filter: 
          event_name: Transfer
      - network: ethereum
        filter: 
          event_name: Approval
```

Really it should accept 

```yaml
contracts: 
  - name: ERC20
    details:
      - network: ethereum
        filter: 
          - event_name: Transfer
          - event_name: Approvall
```

to avoid breaking changes we should also still support 

```yaml
contracts: 
  - name: ERC20
    details:
      - network: ethereum
        filter: 
          event_name: Transfer
      - network: ethereum
        filter: 
          event_name: Approval
```

would make it easier to configure it
