### ISSUE TITLE
Indexer makes one fetch for full block range

### ISSUE THREAD

**Issue by plotchy** [joshstevens19/rindexer#55]
The block range im concerned about gathering events for is ~600K wide.

the resulting rpc call is for `eth_getLogs` for the full range, which always will time out for my use case. Can we configure step size somehow?

The example where the end block is only 100 blocks ahead works perfectly
```yaml
name: kamicsv
project_type: rust
networks:
- name: yominet
  chain_id: 5264468217
  rpc: https://yominet.rpc.caldera.xyz/http
storage:
  csv:
    enabled: true
    path: ./generated_csv
contracts:
- name: World
  details:
  - network: yominet
    address: 0x441e13a25caecad50028e7623a39b91a507bca02
    start_block: '1077466'
    # end_block: '1077566'
    # end_block: '1650276'
  abi: ./abis/World.abi.json
  include_events:
  - ComponentValueSet

```

```
20 July - 14:33:20.921676 TRACE rpc{method="eth_getLogs" params="[{\"fromBlock\":\"0x10713e\",\"toBlock\":\"0x193348\",\"address\":\"0x441e13a25caecad50028e7623a39b91a507bca02\",\"topics\":[\"0x6ac31c38682e0128240cf68316d7ae751020d8f74c614e2a30278afcec8a6073\"]}]"}: take? ("https", yominet.rpc.caldera.xyz): expiration = Some(90s)
```
