### ISSUE TITLE
Fictional logs, no real activity

### ISSUE THREAD

**Issue by ztxtz** [joshstevens19/rindexer#67]
**config:**

```
name: usdc
project_type: no-code
networks:
- name: ethereum
  chain_id: 1
  rpc: https://mainnet.infura.io/v3/redacted
storage:
  postgres:
    enabled: true
contracts:
- name: USDC
  details:
  - network: ethereum
    address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
    start_block: 18000000
    end_block: 20398334
  abi: ./abis/usdc.json
  include_events:
  - approve
```

**run:**

```
> rindexer start all
27 July - 16:31:15.799080  INFO Starting rindexer no code
27 July - 16:31:15.799462  INFO Setting up postgres
27 July - 16:31:15.808902  INFO Creating tables for usdc
27 July - 16:31:15.809138  INFO Creating schema if not exists: usdc_usdc
27 July - 16:31:15.819057  INFO Created tables for usdc
27 July - 16:31:15.823670  INFO Networks enabled: ethereum
27 July - 16:31:15.824396  INFO Events registered to index:
27 July - 16:31:15.824621  INFO Temp dropping constraints relationships from the database for historic indexing for speed reasons
27 July - 16:31:15.824816  INFO Starting GraphQL server
27 July - 16:31:15.843023  INFO Temp dropping indexes from the database for historic indexing for speed reasons
27 July - 16:31:15.865696  INFO Historical indexing complete - time taken: 6.506292ms
27 July - 16:31:15.865711  INFO Applying indexes if any back to the database as historic resync is complete
27 July - 16:31:16.647328  INFO 🦀 GraphQL API ready at http://localhost:3001/graphql Playground - http://localhost:3001/playground
```

**outcome:**

- no RPC queries made
- docker is running, DB is created but **has no tables** in it
- it claims indexing is complete but nothing has been done
