### ISSUE TITLE
All ERC20 transfers to/from a certain address

### ISSUE THREAD

**Issue by nareto** [joshstevens19/rindexer#82]
Hi, thanks for the cool project. Can I use this to index all token transfers to/from a certain address, without knowning in advance the tokens that will be transferred and their ABIs?

**Comment by joshstevens19** [comment]
Hey yes tokens do follow a standard ABI which you can copy in and then use the [filter](https://rindexer.xyz/docs/start-building/yaml-config/contracts#filter) alongside the indexed parameter to filter on them https://rindexer.xyz/docs/start-building/yaml-config/contracts#indexed_1-indexed_2-indexed_3

Lets say I want to get all the tokens which were transferred from `0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045` and to `0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045` starting from block 18600000 (that address is vitaliks btw)

The ABI for transfer is:

```json
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"address",
        "name":"from",
        "type":"address"
      },
      {
        "indexed":true,
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"uint256",
        "name":"value",
        "type":"uint256"
      }
    ],
    "name":"Transfer",
    "type":"event"
  },
```

you can see above from and to are `indexed: true`

I would then do a YAML like this

```yaml
name: Indexer
description: My first rindexer project
repository: https://github.com/joshstevens19/rindexer
project_type: no-code
networks:
  - name: ethereum
    chain_id: 1
    rpc: https://mainnet.gateway.tenderly.co
storage:
  postgres:
    enabled: true
contracts:
  - name: FromTransferEvents
    details:
      - network: ethereum
        start_block: 18600000
        filter:
          event_name: Transfer
        indexed_filters:
          - event_name: Transfer
            indexed_1:
              - "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
    abi: ./abis/RocketTokenRETH.abi.json
    include_events:
      - Transfer
  - name: ToTransferEvents
    details:
      - network: ethereum
        start_block: 18600000
        filter:
          event_name: Transfer
        indexed_filters:
          - event_name: Transfer
            indexed_2:
              - "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
    abi: ./abis/RocketTokenRETH.abi.json
    include_events:
      - Transfer
```

at the moment you can't have 1 filter in the same YAML so it generates you 2 tables but all the data will resync for you.. is that what you was looking for?
